# Generated by Django 5.2 on 2025-04-22 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('castMember_app', '0001_initial'),
        ('category_app', '0001_initial'),
        ('genre_app', '0002_rename_categories_genre_categories_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVideoMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('raw_location', models.CharField(max_length=255)),
                ('encoded_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('ERROR', 'ERROR')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('raw_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('launch_year', models.IntegerField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('published', models.BooleanField()),
                ('rating', models.CharField(choices=[('ER', 'ER'), ('L', 'L'), ('age_10', 'age_10'), ('age_12', 'age_12'), ('age_14', 'age_14'), ('age_16', 'age_16'), ('age_18', 'age_18')], max_length=10)),
                ('banner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_banner', to='video_app.imagemedia')),
                ('cast_members', models.ManyToManyField(related_name='videos', to='castMember_app.castmember')),
                ('categories', models.ManyToManyField(related_name='videos', to='category_app.category')),
                ('genres', models.ManyToManyField(related_name='videos', to='genre_app.genre')),
                ('thumbnail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail', to='video_app.imagemedia')),
                ('thumbnail_half', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail_half', to='video_app.imagemedia')),
                ('thumbnail_trailer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail_trailer', to='video_app.imagemedia')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_media', to='video_app.audiovideomedia')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
