# Generated by Django 5.2 on 2025-04-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='cast_members',
            new_name='cast_members_ids',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='categories',
            new_name='categories_ids',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='genres',
            new_name='genres_ids',
        ),
    ]
