# Generated by Django 5.2 on 2025-04-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_rename_cast_members_video_cast_members_ids_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='cast_members_ids',
            new_name='cast_members',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='categories_ids',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='genres_ids',
            new_name='genres',
        ),
        migrations.AddField(
            model_name='video',
            name='opened',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
