# Generated by Django 5.2 on 2025-04-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_rename_cast_members_ids_video_cast_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiovideomedia',
            name='checksum',
        ),
        migrations.AlterField(
            model_name='audiovideomedia',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('ERROR', 'ERROR')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.CharField(choices=[('ER', 'ER'), ('L', 'L'), ('AGE_10', 'AGE_10'), ('AGE_12', 'AGE_12'), ('AGE_14', 'AGE_14'), ('AGE_16', 'AGE_16'), ('AGE_18', 'AGE_18')], max_length=10),
        ),
    ]
