# Generated by Django 5.2 on 2025-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_remove_audiovideomedia_checksum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovideomedia',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('ERROR', 'ERROR')], default='PENDING', max_length=255),
        ),
    ]
